name: terraform-release
on:
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run
  workflow_run:
    workflows: ["terraform-validate"]
    branches: [main, master]
    types:
      - completed

jobs:
  docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Generate TF Docs
        uses: Dirrk/terraform-docs@v1.0.8
        with:
          tf_docs_output_file: README.md
          tf_docs_git_push: 'true'
          tf_docs_find_dir: .
